#############################################################################
# Makefile for building: FaustLive
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  faudiostream-faustlive.pro
# Template: exe
# Command: C:\Qt\Qt5.2.0\5.2.0\msvc2012\bin\qmake.exe -o Makefile faudiostream-faustlive.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\Qt\Qt5.2.0\5.2.0\msvc2012\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: faudiostream-faustlive.pro ..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\win32-msvc2012\qmake.conf ..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\spec_pre.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\common\shell-win32.conf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\qconfig.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axbase.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_clucene_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_core.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_declarative.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_declarative_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_help.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_network.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_script.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_script_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_webkit.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_webkit_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_webkitwidgets.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_webkitwidgets_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_winextras.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\qt_functions.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\qt_config.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\win32-msvc2012\qmake.conf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\spec_post.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\exclusive_builds.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\default_pre.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\win32\default_pre.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\resolve_config.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\default_post.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\win32\rtti.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\warn_on.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\win32\windows.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\testcase_targets.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\exceptions.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\yacc.prf \
		..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\lex.prf \
		faudiostream-faustlive.pro
	$(QMAKE) -o Makefile faudiostream-faustlive.pro
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\spec_pre.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\common\shell-win32.conf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\qconfig.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_core.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_declarative.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_declarative_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_designer.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_gui.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_help.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_network.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qml.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_quick.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_script.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_script_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_sql.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_svg.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_webkit.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_webkit_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_webkitwidgets.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_winextras.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_xml.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\qt_functions.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\qt_config.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\win32-msvc2012\qmake.conf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\spec_post.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\exclusive_builds.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\default_pre.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\win32\default_pre.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\resolve_config.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\exclusive_builds_post.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\default_post.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\win32\rtti.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\warn_on.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\win32\windows.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\testcase_targets.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\exceptions.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\yacc.prf:
..\..\..\Qt\Qt5.2.0\5.2.0\msvc2012\mkspecs\features\lex.prf:
faudiostream-faustlive.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile faudiostream-faustlive.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) FaustLive.exp
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
